name: Create release with CLI

on:
  workflow_dispatch:
  
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create release
        run: gh release create v0.0.1 --notes "test"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
